/**
 * Local processing-pipeline version — the marker that lets a new
 * daemon build force a re-scan of every previously-uploaded session.
 *
 * Why we need it: file cursors in `state.cursor` track "I've uploaded
 * up to byte N of this JSONL", so a normal restart only ships new
 * events. But when we change the pipeline itself (new summariser
 * model, different sampling, new redaction pass, new segment
 * boundary heuristics), every previously-uploaded segment is now
 * stale even though the underlying JSONL hasn't moved.
 *
 * The fix: bake a single integer into this file. On startup the
 * daemon compares it to the integer written into `state.cursor`'s
 * sibling field. If the compiled-in version is HIGHER than the
 * stored one, wipe every cursor so the next scan re-reads the world
 * from the start, runs every event through the current pipeline,
 * and ships fresh segments.
 *
 * **Bump this whenever the segment shape changes.** Example
 * triggers — DO bump:
 *   • Summariser model swap (e.g. Ollama → bundled Qwen3.5-4B in 0.0.27).
 *   • Summariser prompt change that materially shifts output.
 *   • Excerpt sampling strategy / size cap.
 *   • Segment boundary heuristic change.
 *   • PII redaction rules.
 *   • content_excerpt extraction in a parser (claude-code, codex, etc).
 *
 * Don't bump for:
 *   • Bugfixes that don't affect segment content.
 *   • Heartbeat / discovery / service-install changes.
 *   • Dashboard or backend-only changes.
 *
 * A re-scan REPLACES existing segments by segment_id in place — no
 * duplicates, no orphans. (Where the segment_id hash doesn't change
 * because the inputs didn't change, but the abstract does because the
 * summariser did.)
 */

/** Current local processing-pipeline version. Bump when the
 * pipeline produces materially different segments for the same
 * input events.
 *
 * v1 — pre-versioning baseline (anything that hasn't recorded a
 *      version yet maps to v1).
 * v2 — bundled Qwen3.5-4B summariser, density-first prompt,
 *      char-bounded segments (SEGMENT_MAX_CONTENT_CHARS=12000),
 *      richer excerpt sampling (7×350 chars). Shipped 0.0.28.
 * v3 — client-side cognition pass (Mood + Mind tags appended to
 *      every abstract). The tags travel inside the abstract text, so
 *      they need no dedicated wire field. Shipped 0.0.35.
 * v4 — per-session titles (IngestBatch.session_titles) generated by
 *      the local titler from segment abstracts. Re-scan so every
 *      historical session gets a title, not just ones that change
 *      after the upgrade.
 * v5 — tool_call extraction. Parsers populate RawEvent.tool_calls
 *      (aggregate identity → count map) and emit per-call
 *      ToolCallWire records on IngestBatch.tool_calls. The populated
 *      maps feed turnSurface → segment-boundary embeddings, so
 *      boundaries (and therefore segment_ids) shift; the wipe forces
 *      a full re-parse so historical transcripts get tool_call rows
 *      plus the new `tool_calls` segment tags.
 * v6 — defense-in-depth redaction. The shipped `command_redacted` (and
 *      script summaries) now go through layers 2+3 — the on-device
 *      Privacy Filter (NER/PII) + the local-LLM secret backstop — not
 *      just the regex floor, and the floor's `env_secret` rule was fixed
 *      to catch bare `SECRET=`/`TOKEN=` names. Re-scan so historical
 *      transcripts are re-redacted from the raw logs through the full
 *      stack (the raw never left the device, so only the daemon can).
 */
export const PROCESSING_VERSION = 6;

export interface ProcessingState {
  processingVersion: number | null;
  setProcessingVersion(v: number): void;
  wipeCursors(): void;
}

/**
 * On startup: if the stored processing version is older than the
 * compiled-in one (or absent), wipe cursors and stamp the new
 * version. Returns a description of what happened so the caller can
 * surface it in startup logs.
 */
export function reconcileProcessingVersion(state: ProcessingState): {
  changed: boolean;
  from: number;
  to: number;
} {
  const stored = state.processingVersion ?? 1;
  if (stored >= PROCESSING_VERSION) {
    return { changed: false, from: stored, to: PROCESSING_VERSION };
  }
  state.wipeCursors();
  state.setProcessingVersion(PROCESSING_VERSION);
  return { changed: true, from: stored, to: PROCESSING_VERSION };
}
