/**
 * Local processing-pipeline version — the marker that lets a new
 * daemon build force a re-scan of every previously-uploaded session.
 *
 * Why we need it: file cursors in `state.cursor` track "I've uploaded
 * up to byte N of this JSONL", so a normal restart only ships new
 * events. But when we change the pipeline itself (new summariser
 * model, different sampling, new redaction pass, new segment
 * boundary heuristics), every previously-uploaded segment is now
 * stale even though the underlying JSONL hasn't moved.
 *
 * The fix: bake a single integer into this file. On startup the
 * daemon compares it to the integer written into `state.cursor`'s
 * sibling field. If the compiled-in version is HIGHER than the
 * stored one, wipe every cursor so the next scan re-reads the world
 * from the start, runs every event through the current pipeline,
 * and ships fresh segments.
 *
 * **Bump this whenever the segment shape changes.** Example
 * triggers — DO bump:
 *   • Summariser model swap (e.g. Ollama → bundled Qwen3.5-4B in 0.0.27).
 *   • Summariser prompt change that materially shifts output.
 *   • Excerpt sampling strategy / size cap.
 *   • Segment boundary heuristic change.
 *   • PII redaction rules.
 *   • content_excerpt extraction in a parser (claude-code, codex, etc).
 *
 * Don't bump for:
 *   • Bugfixes that don't affect segment content.
 *   • Heartbeat / discovery / service-install changes.
 *   • Dashboard or backend-only changes.
 *
 * A re-scan REPLACES existing segments by segment_id in place — no
 * duplicates, no orphans. (Where the segment_id hash doesn't change
 * because the inputs didn't change, but the abstract does because the
 * summariser did.)
 */

/** Current local processing-pipeline version. Bump when the
 * pipeline produces materially different segments for the same
 * input events.
 *
 * v1 — pre-versioning baseline (anything that hasn't recorded a
 *      version yet maps to v1).
 * v2 — bundled Qwen3.5-4B summariser, density-first prompt,
 *      char-bounded segments (SEGMENT_MAX_CONTENT_CHARS=12000),
 *      richer excerpt sampling (7×350 chars). Shipped 0.0.28.
 * v3 — client-side cognition pass (Mood + Mind tags appended to
 *      every abstract). The tags travel inside the abstract text, so
 *      they need no dedicated wire field. Shipped 0.0.35.
 * v4 — per-session titles (IngestBatch.session_titles) generated by
 *      the local titler from segment abstracts. Re-scan so every
 *      historical session gets a title, not just ones that change
 *      after the upgrade.
 * v5 — tool_call extraction. Parsers populate RawEvent.tool_calls
 *      (aggregate identity → count map) and emit per-call
 *      ToolCallWire records on IngestBatch.tool_calls. The populated
 *      maps feed turnSurface → segment-boundary embeddings, so
 *      boundaries (and therefore segment_ids) shift; the wipe forces
 *      a full re-parse so historical transcripts get tool_call rows
 *      plus the new `tool_calls` segment tags.
 * v6 — defense-in-depth redaction. The shipped `command_redacted` (and
 *      script summaries) now go through layers 2+3 — the on-device
 *      Privacy Filter (NER/PII) + the local-LLM secret backstop — not
 *      just the regex floor, and the floor's `env_secret` rule was fixed
 *      to catch bare `SECRET=`/`TOKEN=` names. Re-scan so historical
 *      transcripts are re-redacted from the raw logs through the full
 *      stack (the raw never left the device, so only the daemon can).
 * v7 — canonical project slugs. `resolveGitContext` now resolves the git
 *      remote from the MAIN repo for ephemeral `.claude` worktrees (deleted by
 *      parse time), instead of path-guessing a different slug than the repo's
 *      live sessions (`acme` vs `acme/acme`). Re-scan so every historical
 *      session re-resolves to its one canonical remote slug — only the daemon
 *      can, from the raw transcripts on disk.
 * v8 — on-device embedder + PII/NER redactor now actually ship. The daemon
 *      stages the bundled @huggingface/transformers runtime, so (a) the
 *      segmenter's turn embeddings are REAL (semantic cosine-distance
 *      boundaries) instead of the time-gap/max-turns fallback — segment
 *      boundaries, and therefore segment_ids, shift — and (b) redaction layer 2
 *      (the Privacy-Filter NER/PII model) engages on top of the regex floor +
 *      local-LLM backstop. Re-scan so every historical transcript is
 *      re-segmented and re-redacted through the full on-device stack (only the
 *      daemon can, from the raw on disk).
 * v9 — NER redaction model fix. v8's default `openai/privacy-filter` is NOT
 *      loadable by Transformers.js (unsupported `model_type`), so redaction
 *      layer 2 silently fell through to pass-through — it never actually ran.
 *      Switched to `Xenova/bert-base-NER` (q8), a supported architecture that
 *      loads on-device and redacts person/org/location entities. Re-scan so
 *      historical transcripts are re-redacted with the layer that finally works.
 * v10 — richer abstracts + behavioral signal (Insights feature). The summariser
 *      prompt now mandates the concrete action + object + target (repo/branch/
 *      service), and the abstract cap rose 240→400 chars, so abstracts read like
 *      "Triggered a GitHub Actions release for acme/web" instead of a vague
 *      one-liner. Each segment also carries a new privacy-preserving `behavior`
 *      signal (user_turns / correction_count / frustration — counts only, never
 *      raw text) for server-side prompt-friction detection. Re-scan so historical
 *      segments get the richer abstract + the behavior signal (only the daemon
 *      can, from the raw transcripts on disk).
 * v11 — user-intent distillation (Insights v2). Each segment now carries a
 *      `user_intent` distilled from the DEVELOPER'S MESSAGES ONLY (redacted,
 *      on-device): "what did the user ask for / how did they direct the AI" —
 *      the source the rule + skill insights mine instead of the agent's tool
 *      calls (which made every skill look like a git operation). Re-scan so
 *      historical segments gain user_intent — only the daemon can, from the raw
 *      messages on disk.
 * v12 — local-time temporal hints: each segment carries `time_of_day`
 *      (Morning/Midday/Evening/Night) + `cadence` (Weekday/Friday/Weekend),
 *      computed from the engineer's LOCAL wall-clock (only the daemon can — the
 *      server sees UTC). Feed the Time-of-Day + Cadence taxonomy dimensions.
 *      Re-scan so historical segments gain them.
 * v13 — cognition mood + posture hints: the cognition pass now also tags the
 *      working STANCE (posture — ship-it / cautious / questioning / easygoing)
 *      alongside mood, and the daemon ships the PRIMARY mood + posture as
 *      structured `mood`/`posture` hints (not just the abstract suffix) so the
 *      server's Mood + Posture taxonomy dimensions populate — real-data-only, a
 *      bucket per tag that actually occurred. Re-scan so historical segments
 *      gain them.
 * v14 — cognition MIND hint: the daemon now also ships the primary mental-mode
 *      tag (the cognition `meta` field — focused / scattered / in-flow / deliberate)
 *      as a structured `mind` hint, feeding the server's Mind taxonomy dimension
 *      (the cognitive-mode counterpart to Mood + Posture). Re-scan so historical
 *      segments gain it.
 * v15 — authoritative project slugs. The `projects` hint (→ the Workstreams /
 *      "Spend by Repo" dimension) now keys on the git remote read from `.git`
 *      on disk (`resolveAuthoritativeGit`, run before segmentation) instead of
 *      the parser's path guess, which mistook an in-repo `…/src/<a>/<b>` subtree
 *      for a repository (e.g. the subdirectory `accounting/controllers`).
 *      Re-scan so historical segments re-tag to their real owner/repo — only
 *      the daemon can, from the repos on disk.
 * v16 — reserved: the Rust daemon's cutover value (candle BGE embedder +
 *      BERT-NER, different summariser engine). Never shipped on this chain; kept
 *      as a hole so the two daemons' version numbers mean the same thing.
 * v17 — codex token accounting fix. Every codex event ever uploaded carries
 *      0 tokens: the parser read `payload.input_tokens` but codex nests the
 *      counters under `payload.info.last_token_usage`, and a `?? 0` turned the
 *      miss into a zero. Re-scan to recover them — the true counts exist solely
 *      in the rollout JSONL on each device and never reached the server. The
 *      re-scan also re-prices every event against the current rate card, fixing
 *      the historical $0.00 costs for models that had no rate row.
 * v18 — provenance tiering. Repo slugs now carry their `slug_source` provenance
 *      end to end: the `projects` hint reads the first VERIFIED slug in the
 *      slice (confidence tiered 1 / 0.5, `reason` = the marker verbatim) and
 *      session-metadata repo refs ship `git` vs `git_guess` from the same
 *      predicate. Re-scan so historical segments re-derive their projects
 *      hints + repo ref sources — only the daemon can, from the events on
 *      disk.
 */
export const PROCESSING_VERSION = 18;

export interface ProcessingState {
  processingVersion: number | null;
  setProcessingVersion(v: number): void;
  wipeCursors(): void;
}

/**
 * On startup: if the stored processing version is older than the
 * compiled-in one (or absent), wipe cursors and stamp the new
 * version. Returns a description of what happened so the caller can
 * surface it in startup logs.
 */
export function reconcileProcessingVersion(state: ProcessingState): {
  changed: boolean;
  from: number;
  to: number;
} {
  const stored = state.processingVersion ?? 1;
  if (stored >= PROCESSING_VERSION) {
    return { changed: false, from: stored, to: PROCESSING_VERSION };
  }
  state.wipeCursors();
  state.setProcessingVersion(PROCESSING_VERSION);
  return { changed: true, from: stored, to: PROCESSING_VERSION };
}
